name: deploy-preview

on:
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_REPO: ghcr.io/${{ github.repository }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Log into registry
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.IMAGE_REPO }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.IMAGE_REPO }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_REPO }}:buildcache,mode=max

      - name: Deploy Preview to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_KEY }}
          script: |
            echo ${{ secrets.CR_PAT }} | docker login ${{ env.REGISTRY }} --username ${{ secrets.CR_USERNAME }} --password-stdin
            docker pull ${{ env.IMAGE_REPO }}:pr-${{ github.event.number }}
            docker stop preview-pr${{ github.event.number }}
            docker run -d --rm --network hmci-network --name preview-pr${{ github.event.number }} \
              --label "traefik.enable=true" \
              --label "traefik.http.routers.preview-pr${{ github.event.number }}.rule=Host(\`preview-pr${{ github.event.number }}.${{ secrets.BASE_DOMAIN }}\`)" \
              --label "traefik.http.routers.preview-pr${{ github.event.number }}.tls=true" \
              --label "traefik.http.routers.preview-pr${{ github.event.number }}.tls.certresolver=letsencrypt" \
              ${{ env.IMAGE_REPO }}:pr-${{ github.event.number }}

      - name: Comment Preview URL to PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Preview available at https://preview-pr${{ github.event.number }}.${{ secrets.BASE_DOMAIN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
