name: dispose-preview

on:
  pull_request:
    branches: [main]
    types: [closed]

env:
  REGISTRY: ghcr.io
  IMAGE_REPO: ghcr.io/${{ github.repository }}

jobs:
  dispose-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Delete image from registry
        if: ${{ env.REGISTRY == 'ghcr.io' }}
        uses: bots-house/ghcr-delete-image-action@v1.0.0
        with:
          owner: ${{ github.event.repository.owner.login }}
          name: ${{ github.event.repository.name }}
          token: ${{ secrets.CR_PAT }}
          tag: pr-${{ github.event.number }}

      - name: Dispose Preview from VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_KEY }}
          script: |
            docker stop preview-pr${{ github.event.number }}
            docker rmi ${{ env.IMAGE_REPO }}:pr-${{ github.event.number }}
